name: main pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:

    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
    
    - name: install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: run staticcheck
      run: make lint
  
  build:
    runs-on: ubuntu-20.04
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v3
    
    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
    
    - name: go tests
      run: make test
    
    - name: go build
      run: make build