name: main pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - uses: sbdchd/squawk-action@v1
        with:
          pattern: "migrations/*.sql"
          version: "latest"
  
  build:
    needs: [ check-migrations ]
    
    runs-on: ubuntu-20.04
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.4
    
    - name: go tests
      run: make test