name: main pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Mandatory unless "latest" is set below.
    - uses: ariga/atlas-action@v0
      with:
        dir: migrations
        dir-format: golang-migrate
  
  build:
    needs: [ check-migrations ]
    
    runs-on: ubuntu-20.04
    steps:
    
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.4
    
    - name: go tests
      run: make test